version: '3.1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_DATABASE: wp_explorejobs
      MYSQL_USER: explore
      MYSQL_PASSWORD: explore
      MYSQL_ROOT_PASSWORD: secret

    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --bind-address=0.0.0.0
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
